/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.Utils;
import model.Financeiro;
import model.Gestor;
import model.Funcionario;
import model.Voluntario;
/**
 *
 * @author Leo
 */
public class TelaVoluntario extends javax.swing.JFrame {
Voluntario voluntario = new Voluntario();
Financeiro financeiro = new Financeiro();
Funcionario funcionario = new Funcionario(); 
Gestor gestor = new Gestor();
Utils util = Utils.getInstancia();
   /**
     * Creates new form TelaGestor
     */
    public TelaVoluntario() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpDoar = new javax.swing.JPanel();
        receitasLabel = new javax.swing.JLabel();
        receitasText = new javax.swing.JTextField();
        despesasLabel = new javax.swing.JLabel();
        btnInserirReceita = new javax.swing.JButton();
        btnInserirDespesa = new javax.swing.JButton();
        despesasText1 = new javax.swing.JTextField();
        jpEvento = new javax.swing.JPanel();
        jlevento = new javax.swing.JLabel();
        txEvento = new javax.swing.JTextField();
        jbconsultarEvento = new javax.swing.JButton();
        jspEvento = new javax.swing.JScrollPane();
        txtareaEvento = new javax.swing.JTextArea();
        jpTrabalho = new javax.swing.JPanel();
        jlTrabalho = new javax.swing.JLabel();
        txTrabalho = new javax.swing.JTextField();
        jbconsultarTrabalho = new javax.swing.JButton();
        jspTrabalho = new javax.swing.JScrollPane();
        txtareaTrabalho = new javax.swing.JTextArea();
        jbAceitarTrabalho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        receitasLabel.setText("DINHEIRO");

        receitasText.setToolTipText("R$");
        receitasText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                receitasTextKeyTyped(evt);
            }
        });

        despesasLabel.setText("ALIMENTO");

        btnInserirReceita.setText("Doar");
        btnInserirReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirReceitaActionPerformed(evt);
            }
        });

        btnInserirDespesa.setText("Doar");
        btnInserirDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirDespesaActionPerformed(evt);
            }
        });

        despesasText1.setToolTipText("Kg");
        despesasText1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                despesasText1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpDoarLayout = new javax.swing.GroupLayout(jpDoar);
        jpDoar.setLayout(jpDoarLayout);
        jpDoarLayout.setHorizontalGroup(
            jpDoarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDoarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpDoarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receitasLabel)
                    .addComponent(despesasLabel))
                .addGap(18, 18, 18)
                .addGroup(jpDoarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receitasText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(despesasText1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDoarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserirReceita)
                    .addComponent(btnInserirDespesa))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jpDoarLayout.setVerticalGroup(
            jpDoarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDoarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jpDoarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receitasLabel)
                    .addComponent(receitasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirReceita))
                .addGap(18, 18, 18)
                .addGroup(jpDoarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(despesasLabel)
                    .addComponent(btnInserirDespesa)
                    .addComponent(despesasText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DOAÇÕES", jpDoar);

        jlevento.setText("EVENTOS");

        jbconsultarEvento.setText("Consultar");
        jbconsultarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconsultarEventoActionPerformed(evt);
            }
        });

        txtareaEvento.setColumns(20);
        txtareaEvento.setRows(5);
        jspEvento.setViewportView(txtareaEvento);

        javax.swing.GroupLayout jpEventoLayout = new javax.swing.GroupLayout(jpEvento);
        jpEvento.setLayout(jpEventoLayout);
        jpEventoLayout.setHorizontalGroup(
            jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEventoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jspEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpEventoLayout.createSequentialGroup()
                        .addComponent(jlevento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jbconsultarEvento)
                .addGap(11, 11, 11))
        );
        jpEventoLayout.setVerticalGroup(
            jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEventoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jpEventoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlevento)
                    .addComponent(jbconsultarEvento)
                    .addComponent(txEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jspEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("EVENTOS", jpEvento);

        jlTrabalho.setText("TRABALHO");

        txTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTrabalhoActionPerformed(evt);
            }
        });

        jbconsultarTrabalho.setText("Consultar");
        jbconsultarTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconsultarTrabalhoActionPerformed(evt);
            }
        });

        txtareaTrabalho.setColumns(20);
        txtareaTrabalho.setRows(5);
        jspTrabalho.setViewportView(txtareaTrabalho);

        jbAceitarTrabalho.setText("Aceitar");
        jbAceitarTrabalho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceitarTrabalhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTrabalhoLayout = new javax.swing.GroupLayout(jpTrabalho);
        jpTrabalho.setLayout(jpTrabalhoLayout);
        jpTrabalhoLayout.setHorizontalGroup(
            jpTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTrabalhoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlTrabalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jpTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txTrabalho)
                    .addComponent(jspTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jpTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbconsultarTrabalho)
                    .addComponent(jbAceitarTrabalho))
                .addGap(11, 11, 11))
        );
        jpTrabalhoLayout.setVerticalGroup(
            jpTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTrabalhoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jpTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbconsultarTrabalho)
                    .addComponent(jlTrabalho))
                .addGap(18, 18, 18)
                .addGroup(jpTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jspTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAceitarTrabalho))
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("TRABALHO", jpTrabalho);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbconsultarTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconsultarTrabalhoActionPerformed
        funcionario = gestor.consultaFuncionario(txTrabalho.getText());

        String resultado = funcionario.toString();
        txtareaTrabalho.setText(resultado);
    }//GEN-LAST:event_jbconsultarTrabalhoActionPerformed

    private void despesasText1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_despesasText1KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_despesasText1KeyTyped

    private void btnInserirDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirDespesaActionPerformed
        financeiro.setDespesa(financeiro.getDespesa() + Double.parseDouble(despesasText1.getText()));
        String str = Double.toString(financeiro.getDespesa());
        despesasText1.setText(str);
        despesasText1.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnInserirDespesaActionPerformed

    private void btnInserirReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirReceitaActionPerformed
        financeiro.setReceita(financeiro.getReceita() + Double.parseDouble(receitasText.getText()));
        String str = Double.toString(financeiro.getReceita());
        receitasText.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnInserirReceitaActionPerformed

    private void receitasTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_receitasTextKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_receitasTextKeyTyped

    private void jbconsultarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconsultarEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbconsultarEventoActionPerformed

    private void jbAceitarTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceitarTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbAceitarTrabalhoActionPerformed

    private void txTrabalhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTrabalhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTrabalhoActionPerformed

   
       public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVoluntario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVoluntario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserirDespesa;
    private javax.swing.JButton btnInserirReceita;
    private javax.swing.JLabel despesasLabel;
    private javax.swing.JTextField despesasText1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbAceitarTrabalho;
    private javax.swing.JButton jbconsultarEvento;
    private javax.swing.JButton jbconsultarTrabalho;
    private javax.swing.JLabel jlTrabalho;
    private javax.swing.JLabel jlevento;
    private javax.swing.JPanel jpDoar;
    private javax.swing.JPanel jpEvento;
    private javax.swing.JPanel jpTrabalho;
    private javax.swing.JScrollPane jspEvento;
    private javax.swing.JScrollPane jspTrabalho;
    private javax.swing.JLabel receitasLabel;
    private javax.swing.JTextField receitasText;
    private javax.swing.JTextField txEvento;
    private javax.swing.JTextField txTrabalho;
    private javax.swing.JTextArea txtareaEvento;
    private javax.swing.JTextArea txtareaTrabalho;
    // End of variables declaration//GEN-END:variables
}
